plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace "me.ocv.partyup"
    compileSdk 36

    defaultConfig {
        applicationId "me.ocv.partyup"
        minSdk 21
        targetSdk 35
        versionCode 10000
        versionName "1.0.0"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            storeFile file(env.fetch("RELEASE_JKS_FILE"))
            storePassword env.fetch("RELEASE_JKS_PASS")
            keyAlias env.fetch("RELEASE_KEY_ALIS")
            keyPassword env.fetch("RELEASE_KEY_PASS")
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
        buildConfig true
    }

    lint {
        checkReleaseBuilds false
    }

    // "Lint found fatal errors while assembling a release target:"
    // "Google Play requires that apps target API level 29 or higher"
    // lol how about no
}

dependencies {
    implementation libs.material
    implementation libs.preference
    implementation libs.zixing.core
}
